driver:
  name: docker
  use_sudo: false

provisioner:
  name: habitat
  hab_sup_origin: core
  hab_sup_name: sup
  install_latest_artifact: true

platforms:
  - name: ubuntu-16.04

suites:
  - name: grafana
    provisioner:
      package_origin: fastrobot
      package_name: grafana